adding s3 & cloudfront event parsers
lumigo-io/python_tracer pull request #147
Opened 2020-09-24 12:33 UTC by GuyMoses

2020-09-25 07:24 UTC, uri-p requested changes

2020-09-25 07:24 UTC, uri-p commented on src/test/unit/parsers/test_event_parser.py
> +                                "name": "testingbuckets3testing",
Seems like this is redundant with arn

2020-09-25 07:24 UTC, uri-p commented on src/test/unit/parsers/test_event_parser.py
> +                                "name": "testingbuckets3testing",
Maybe we can also drop ownerIdentity

2020-09-25 07:24 UTC, uri-p commented on src/test/unit/parsers/test_event_parser.py
> +                                "eTag": "714ee5196a5c0a6e6b9019caa7b6e970",
What is etag ? sequencer?
Can we drop them?

2020-09-29 07:57 UTC, uri-p approved these changes

2020-09-29 08:25 UTC, doriaviram approved these changes

2020-10-06 12:28 UTC, merged