RD 3761 - pymongo
lumigo-io/python_tracer pull request #150
Opened 2020-10-04 16:47 UTC by saartochner

2020-10-05 14:32 UTC, doriaviram requested changes
Good job !

2020-10-05 14:32 UTC, doriaviram commented on src/lumigo_tracer/tracer.py
> +    def lambda_wrapper(*args, **kwargs):
Check this condition outside the lambda wrapper, and just return `func` if it switched off

2020-10-05 14:32 UTC, doriaviram commented on src/lumigo_tracer/tracer.py
> +    return "\n".join(enhanced_lines)
Lets talk, I think all this part is useless

2020-10-05 14:32 UTC, doriaviram commented on src/lumigo_tracer/tracer.py
> +                TimeoutMechanism.stop()
Not any way we want to stop the `TimeoutMechanism` ?

2020-10-05 14:57 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +        result["arn"] = event["Records"][0]["s3"]["bucket"]["arn"]
I don't want it to be safe :)
If I'm failing - then I want that the trigger will be unknown 🤔

2020-10-05 14:57 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +        result["arn"] = event["Records"][0]["s3"]["bucket"]["arn"]
the "safe" is above, in `parse_triggered_by`, that fallback to unknown in error

2020-10-05 15:01 UTC, saartochner commented on src/lumigo_tracer/wrappers/http/sync_http_wrappers.py
> +    last_event = SpansContainer.get_span().get_last_span()
you're right,
we absolutely assume synchronous executions! (That's why we called it `sync_http_wrapper`)

2020-10-06 08:00 UTC, doriaviram approved these changes

2020-10-11 15:17 UTC, merged