RD-4996 added memory over time to singe transaction
lumigo-io/python_tracer pull request #191
Opened 2021-05-10 10:56 UTC by OrrLumigo

2021-05-10 15:17 UTC, saartochner requested changes
GJ!

2021-05-10 15:17 UTC, saartochner commented on src/lumigo_tracer/extension/extension.py
> -        self.sampler.stop_sampling()
there should be a single sampler.
Maybe you can change this sampler to collect two metrics!

2021-05-10 15:17 UTC, saartochner commented on src/lumigo_tracer/extension/extension.py
> +            memoryUsageTime=[s.dump() for s in self.memory_sampler.get_samples()],
```suggestion
            cpuUsageTime=[s.dump() for s in self.sampler.get_cpu_samples()],
            memoryUsageTime=[s.dump() for s in self.sampler.get_memory_samples()],
```
This is what I would have expect

2021-05-11 09:08 UTC, saartochner commented on src/lumigo_tracer/extension/extension_utils.py
> +    with lumigo_safe_execute("Extension: get cpu time"):
```suggestion
    with lumigo_safe_execute("Extension: get memory usage"):
```

2021-05-11 14:49 UTC, OrrLumigo commented on src/test/unit/extension/conftest.py
> -def mock_linux_files():
but this return a const value for readlines..

2021-05-12 08:45 UTC, saartochner commented on src/lumigo_tracer/extension/extension_utils.py
> +            mem_total_pattern = re.compile(r'(MemTotal)[:][ ]*([0-9]*)')
put it as a constant . you don't need to compile it in every sample

2021-05-12 10:07 UTC, saartochner approved these changes

2021-05-12 12:20 UTC, merged