A rd 5221 alb triggered by support
lumigo-io/python_tracer pull request #198
Opened 2021-06-21 08:14 UTC by sapirlumigo

2021-06-22 08:21 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +        )  # noqa
```suggestion
        ) 
```
I think

2021-06-22 08:21 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +            event.get("requestContext", {}).get("elb") is not None  # noqa
```suggestion
            event.get("requestContext", {}).get("elb") is not None 
```
I think

2021-06-22 08:28 UTC, sapirlumigo commented on src/lumigo_tracer/event/event_trigger.py
> +            event.get("requestContext", {}).get("elb") is not None  # noqa
src/lumigo_tracer/event/event_trigger.py:93:13: W503 line break before binary operator

2021-06-22 08:28 UTC, sapirlumigo commented on src/lumigo_tracer/event/event_trigger.py
> +        )  # noqa
src/lumigo_tracer/event/event_trigger.py:93:13: W503 line break before binary operator

2021-06-22 08:28 UTC, saartochner requested changes
GJ!

2021-06-22 08:28 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +        "messageId": event.get("requestContext", {}).get("requestId", ""),
I don't think that this ever exists..
https://docs.aws.amazon.com/lambda/latest/dg/services-alb.html

2021-06-22 08:28 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +        "resource": event.get("resource", ""),
never exists

2021-06-22 08:28 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> +        result["stage"] = event["requestContext"].get("stage")
can you try to create an elb/alb with stage?
I don't know if this is possible...

2021-06-22 08:28 UTC, saartochner commented on src/test/unit/event/test_event_trigger.py
> +                "stage": None,
this is a good hint that these fields are unnecessary 🤔

2021-06-23 11:56 UTC, saartochner approved these changes

2021-06-23 12:46 UTC, merged