RD-9485 - recursive parse triggeredBy
lumigo-io/python_tracer pull request #265
Opened 2022-11-02 14:05 UTC by saartochner

2022-11-02 14:28 UTC, saartochner commented on src/lumigo_tracer/event/event_trigger.py
> -def parse_triggered_by(event: dict):  # type: ignore[no-untyped-def,type-arg]
this file was split into many files - a file per trigger type.

2022-11-09 11:46 UTC, saartochner commented on src/test/unit/wrappers/http/test_sync_http_wrappers.py
> +        done = False
This is a fix to a flaky test (work in some machines, and doesn't work in other)

2022-11-20 08:55 UTC, saartochner commented on src/test/unit/wrappers/http/test_sync_http_wrappers.py
> -        conn = http.client.HTTPConnection("www.google.com")
fix another flaky - google sometimes throttle us

2022-11-20 15:14 UTC, nirLumigo requested changes
Nice! :)

2022-11-20 15:14 UTC, nirLumigo commented on src/lumigo_tracer/event/event_trigger.py
> +    if level >= Configuration.chained_services_max_depth:
Great catch! 💪

2022-11-20 15:58 UTC, saartochner commented on src/lumigo_tracer/event/trigger_parsing/event_trigger_base.py
> +        except Exception:
We talked about it: this is an accepted flow, we shouldn't log it

2022-11-20 16:04 UTC, saartochner commented on src/test/component/test_component.py
> +    assert events[0]["info"]["httpInfo"]["host"] == f"sqs.{region}.amazonaws.com"
yes. This is the old endpoint of SQS.
the docker's boto3 version was changed

2022-11-21 09:59 UTC, nirLumigo approved these changes

2022-11-23 08:59 UTC, merged